### ISSUE TITLE
Calculated regionSize for DeletableBloomFilter is wrong, causes out-of-bounds panic

### ISSUE THREAD

**Issue by betawaffle** [tylertreat/BoomFilters#24]
The way `regionSize` is calculated for `DeletableBloomFilter` does not mesh with the size of `collisions`. If a value is hashed to a high index (`m - 1` for example), if there is a collision at that index, the index into `collisions` is out of bounds (equal to `r`). It seems like maybe integer truncation isn't factored in during the calculation of `regionSize` or during `idx/d.regionSize`. If not that, then `collisions` should have `r + 1` buckets.

This was discovered in [cayleygraph/cayley](https://github.com/cayleygraph/cayley/blob/master/graph/kv/indexing.go) using this panic:
```
panic: runtime error: index out of range

goroutine 2752066 [running]:
github.com/tylertreat/BoomFilters.(*Buckets).setBits(0xc42016e4e0, 0x100000078, 0xc400000001)
        /home/kevin/go/src/github.com/tylertreat/BoomFilters/buckets.go:101 +0x128
github.com/tylertreat/BoomFilters.(*Buckets).Set(0xc42016e4e0, 0x78, 0x1, 0xc42016e4b0)
        /home/kevin/go/src/github.com/tylertreat/BoomFilters/buckets.go:62 +0x53
github.com/tylertreat/BoomFilters.(*DeletableBloomFilter).Add(0xc42001e240, 0xc4200243c0, 0x18, 0x18, 0x8, 0x0)
        /home/kevin/go/src/github.com/tylertreat/BoomFilters/deletable.go:96 +0x106
github.com/cayleygraph/cayley/graph/kv.(*QuadStore).bloomAdd(0xc4200dc0a0, 0xc44090cea0)
        /home/kevin/go/src/github.com/cayleygraph/cayley/graph/kv/indexing.go:943 +0xca
github.com/cayleygraph/cayley/graph/kv.(*QuadStore).indexLink(0xc4200dc0a0, 0x8d1e20, 0xc429580d60, 0xc44090cea0, 0x0, 0x0)
        /home/kevin/go/src/github.com/cayleygraph/cayley/graph/kv/indexing.go:527 +0x22d
github.com/cayleygraph/cayley/graph/kv.(*QuadStore).indexLinks(0xc4200dc0a0, 0x8d1b60, 0xc420022138, 0x8d1e20, 0xc429580d60, 0xc6558cc000, 0x66d63, 0x66d63, 0x0, 0xc48977d8e7086225)
        /home/kevin/go/src/github.com/cayleygraph/cayley/graph/kv/indexing.go:510 +0x116
github.com/cayleygraph/cayley/graph/kv.(*QuadStore).ApplyDeltas(0xc4200dc0a0, 0xc608642000, 0x66d63, 0x75b8e, 0x8c0001, 0x0, 0x0)
        /home/kevin/go/src/github.com/cayleygraph/cayley/graph/kv/indexing.go:400 +0xa54
github.com/cayleygraph/cayley/writer.(*Single).ApplyTransaction(0xc4262440a0, 0xc48c656020, 0xc50ef3d4c0, 0x8cfc00)
        /home/kevin/go/src/github.com/cayleygraph/cayley/writer/single.go:121 +0x5b
```

**Comment by tylertreat** [comment]
Thanks for the report. I was able to reproduce and [this](https://github.com/tylertreat/BoomFilters/commit/e4c39d49fb322169c2932fc10b0c5544318add78) appears to fix it. Let me know if you still encounter problems.
