### ISSUE TITLE
topk panics if added elements count is less than total elements defined.

### ISSUE THREAD

**Issue by venugopalkandru** [tylertreat/BoomFilters#3]
Defined a topk and declared total elements count of 10.
But added only 7 elements.
topk fails if executed to get elements.

```go
package main

import (
    "fmt"
    "github.com/tylertreat/BoomFilters"
)

const NUM_TOPK_ELEMENTS = 10

func main() {
    topk := boom.NewTopK(0.001, 0.99, NUM_TOPK_ELEMENTS) 

    topk.Add([]byte(`bob`)).Add([]byte(`bob`)).Add([]byte(`bob`))
    topk.Add([]byte(`tyler`)).Add([]byte(`tyler`)).Add([]byte(`tyler`)).Add([]byte(`tyler`))
    topk.Add([]byte(`fred`))
    topk.Add([]byte(`alice`)).Add([]byte(`alice`)).Add([]byte(`alice`)).Add([]byte(`alice`))
    topk.Add([]byte(`james`))
    topk.Add([]byte(`fred`))
    topk.Add([]byte(`sara`)).Add([]byte(`sara`))
    topk.Add([]byte(`bill`))

    for i, element := range topk.Elements() {
        fmt.Println(i, string(element))
    }   

    // Restore to initial state.
    topk.Reset()
}
```
```go
root@server ~/go # go run /tmp/test_tk.go 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x4507d1]

goroutine 1 [running]:
github.com/tylertreat/BoomFilters.(*elementHeap).Less(0xc20801e180, 0x9, 0x4, 0xa)
        <autogenerated>:8 +0xb1
container/heap.down(0x7f1db00a6910, 0xc20801e180, 0x4, 0xa)
        /root/.gvm/gos/go1.4/src/container/heap/heap.go:111 +0xb4
container/heap.Init(0x7f1db00a6910, 0xc20801e180)
        /root/.gvm/gos/go1.4/src/container/heap/heap.go:45 +0x81
github.com/tylertreat/BoomFilters.(*TopK).Elements(0xc20801e080, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4/global/src/github.com/tylertreat/BoomFilters/topk.go:76 +0x211
main.main()
        /tmp/test_tk.go:20 +0x4c0

goroutine 2 [runnable]:
runtime.forcegchelper()
        /root/.gvm/gos/go1.4/src/runtime/proc.go:90
runtime.goexit()
        /root/.gvm/gos/go1.4/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /root/.gvm/gos/go1.4/src/runtime/mgc0.go:82
runtime.goexit()
        /root/.gvm/gos/go1.4/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /root/.gvm/gos/go1.4/src/runtime/malloc.go:712
runtime.goexit()
        /root/.gvm/gos/go1.4/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
```

**Comment by tylertreat** [comment]
Fixed in https://github.com/tylertreat/BoomFilters/pull/9.
